### ISSUE TITLE
Symphony Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by marciotoledo** [symphonists/reflectionfield#19]
I enabled extension and try create new section and shows this error.

Symphony Warning: Invalid argument supplied for foreach()

http://files.toledointeractive.com/image/170P150C3y26

**Comment by savosik** [comment]
![image](https://cloud.githubusercontent.com/assets/16825666/15741539/d0ae66f6-28c2-11e6-8b44-c1c582a881ac.png)

commit to reflection field didnt help

**Comment by nitriques** [comment]
Which version of Symphony ? And version of the extension ?

**Comment by brendo** [comment]
The screenshot says Association Field? Is this issue in the wrong place?

**Comment by savosik** [comment]
@brendo sorry, you're right..  Problem was here https://github.com/mazedigital/association_output/issues/10

**Comment by brendo** [comment]
All good!
