### ISSUE TITLE
Symphony Warning: DOMXPath::evaluate(): Invalid expression

### ISSUE THREAD

**Issue by cylkee** [symphonists/reflectionfield#31]
```
An error occurred in /some-path/extensions/reflectionfield/fields/field.reflection.php around line 390

    385 // Find queries:
    386 preg_match_all('/\{[^\}]+\}/', $expression, $matches);
    387
    388 // Find replacements:
    389 foreach ($matches[0] as $match) {
    390 $result = $xpath->evaluate('string(//' . trim($match, '{}') . ')');
    391
    392 if (!is_null($result)) {
    393 $replacements[$match] = trim($result);
    394 } else { 
```

The reflection is complex using XPath functions: `{entry/label} ({substring-before(entry/company/item, ' General Ltd.')}s)`

The same reflection works in v1.4.2 on Symphony 2.6.11.  If I change it to a simple reflection on this v2.0.0 instance, it works with `{entry/label} ({entry/company/item})`

Also, something weird is going on.  I did a `git submodule add git://github.com/symphonists/reflectionfield.git extensions/reflectionfield --recursive` on a new installation of `2.6.11` and it gave me `reflectionfield 2.0.0`.  See also version disorder on:

[GitHub](https://github.com/symphonists/reflectionfield/releases)  
![reflectionfield1](https://cloud.githubusercontent.com/assets/11518707/22895457/7d75ebf0-f214-11e6-970d-253dd31ef09a.png)

and

[symphonyextensions.com](http://symphonyextensions.com/extensions/reflectionfield/)  
![reflectionfield2](https://cloud.githubusercontent.com/assets/11518707/22895462/7edd42fe-f214-11e6-979c-e9ac33a17d1d.png)

**Comment by nitriques** [comment]
The git command you set will fetch the latest version so 2.0.0 is the latest one. The bug is on the extension site. I've created the [2.0.0](https://github.com/symphonists/reflectionfield/releases/tag/2.0.0) release, thanks.

Also, 2.0.0 introduced changes. Did you check the read me ?

**Comment by cylkee** [comment]
Thanks, @nitriques.  I will try again at a later date when I have a Symphony installation I can test on..  I did check the readme, but it'd be good to have some example XPath expressions in there (one basic, one complex, one referencing a utility perhaps).  I'd just like to check that it's intended behaviour that reflectionfield will interpret any XPath expression including those with functions?  Because it seems like the version change breaks function usage, as per my original post.

**Comment by cylkee** [comment]
Slightly unrelated, the readme is becoming mangled on [symphonyextensions.com](http://symphonyextensions.com/extensions/reflectionfield/) with headings overlapping paragraphs (visible in screenshot above). I would open an issue on symphony-extensions-network, but it seems only to be reflectionfield's readme.

Also the code block is rendering as one wrapping line (but maybe that is a site-wide issue).

**Comment by twiro** [comment]
> _Slightly unrelated, the readme is becoming mangled on symphonyextensions.com_

Noticed that too and think a separate issue at the symphony-extension-network would be the best to discuss this as the problem isn't limited to rhe reflection field repo.

**symphonyextensions.com** is very restrictive regarding the formatting of the readme (it can't handle multiple H1s (like in this case), tables or code-blocks that use spaces instead of tabs). The question is if we can/will/should try to fix this on symphonyextensions.com or if we should set up more restrictive rules/recommendations regarding how to write/format the readme-files of extension-repos.

Having said this I think I'll best simply copy this paragraph and post a new issue in the SEN-repo... Any further discussion regarding this can be held over there!

**Comment by twiro** [comment]
> _Any further discussion regarding this can be held over there!_

**https://github.com/symphonists/symphony-extensions-network/issues/16**

**Comment by nitriques** [comment]
@cylkee so the problem is the `substring-before` part ? It works without it ?

**Comment by cylkee** [comment]
Yes.

`{entry/label} ({substring-before(entry/company/item, ' General Ltd.')}s)` works in v1.4.2 and at that time not in v2.0.0.

Removing the XPath function, forming simply `{entry/label} ({entry/company/item})` made it work in v2.0.0

I've since gone back to v1.4.2.

Is it the case that it should accept any XPath, which includes functions?  Or are there restrictions not disclosed in the Readme?

**Comment by nitriques** [comment]
Maybe @nilshoerrmann knows why it would crash, since he made most of the code of version 2.0.0.

Does it works if the code is only `{substring-before(entry/company/item, ' General Ltd.')}` ?

**Comment by nitriques** [comment]
I think I've found it: https://github.com/symphonists/reflectionfield/compare/33f39845e4136c245ff26e8ffe4277a76f336af6...55a34e7?w=0#diff-dadafdd0b64efb75d1d13bd715068ccaR390

vs

https://github.com/symphonists/reflectionfield/compare/33f39845e4136c245ff26e8ffe4277a76f336af6...55a34e7?w=0#diff-dadafdd0b64efb75d1d13bd715068ccaL362

Try to remove the // ? or and the @ ?

**Comment by cylkee** [comment]
> Does it works if the code is only `{substring-before(entry/company/item, ' General Ltd.')}` ?

@nitriques No.

**Comment by nitriques** [comment]
@cylkee This might be a good start: https://help.github.com/articles/creating-a-pull-request/

> If I amend to:

That was the fix I hope to land! I'll fix this right now. Thanks!
