### ISSUE TITLE
Reflection field populated into XML or param pool even if it is empty

### ISSUE THREAD

**Issue by jurajkapsz** [symphonists/reflectionfield#32]
Reflection field is being added into `XML output` or `param pool` via `datasource` even if its value is empty.

Is this a desired behavior?
My guess would be not to include it in the XML tree or param pool when there is no value, so it's not part of e.g. cache or XML tree / param pool, as I think this is the default behavior of other fields output.

I was about to write that this occurs only with reflection field, but I found it also by [Multilingual Text Box](https://github.com/DeuxHuitHuit/multilingual_field).

I understand that it is probably because its database value entry is being kept even if it's empty, while other fields like the basic `Text field` or `Textarea field` delete their entries from database when they are not filled out.

**Comment by nitriques** [comment]
> Is this a desired behavior?

That's a good question. But right now, it's really not enforced in the core, hence, I would not consider this a bug. 

But I think that extensions should mimic the "core" field behavior, so I would accept a PR, that fixes this. Thanks!
