### ISSUE TITLE
[v2.0.2] Ignores XSLT Utility

### ISSUE THREAD

**Issue by jurajkapsz** [symphonists/reflectionfield#34]
It appears that the latest version v2.0.2 does not evaluate XSLT Utility `{something}` expressions.

Going back to v2.0.1, everything is fine.

**Comment by nitriques** [comment]
> XSLT Utility 

What do you mean by this ? Calling an external xslt file ?

**Comment by jurajkapsz** [comment]
> Calling an external xslt file ?

Yes, the optional xslt file in field's properties.

![image](https://cloud.githubusercontent.com/assets/2209893/26795399/cc629402-4a25-11e7-8814-23c60e2ee23f.png)

**Comment by nitriques** [comment]
Oh well. This is a bug. I sadly do not have the time to fix it right now tho, (sorry).
And I really wonder why [this simple change](https://github.com/symphonists/reflectionfield/compare/2.0.1...2.0.2) would make that...

**Comment by jurajkapsz** [comment]
> I sadly do not have the time to fix it right now tho, (sorry).

That's ok, previous version v2.0.1 works fine.

**Comment by nitriques** [comment]
Can you try to:

1. Update to 2.0.2
1. Change your xpath from `{something}` to `//{something}`

it should work !

**Comment by nitriques** [comment]
@jurajkapsz ping ?

**Comment by jurajkapsz** [comment]
> 1. Update to 2.0.2
> 2. Change your xpath from {something} to {//something}

Ok, I've tested it and it works flawlessly. Thanks very much @nitriques !

**Comment by jurajkapsz** [comment]
> Ok, I've tested it and it works flawlessly.

One note though: the `//` now has to be added to the standalone xpath `Expression` too, like:

![image](https://user-images.githubusercontent.com/2209893/27761304-b526d1ca-5e59-11e7-94d7-14d45b48dbd0.png)

**Comment by nitriques** [comment]
> One note though: the // now has to be added to the standalone xpath Expression too, like:

Yup. This was previously not-needed, but it is now because we allow users to enter xpath functions, which was not possible if the // is hardcoded. Thanks!

**Comment by jurajkapsz** [comment]
Ok, that makes sense, thanks!
